### ISSUE TITLE
No attribute dispatch error

### ISSUE THREAD

**Issue by adam-hartshorne** [JiaYaobo/fenbux#1]
I have just pip installed fenbux, but upon attempting to import it I get the following error message.

```
    import fenbux as fbx
  File "/opt/homebrew/anaconda3/envs/jax/lib/python3.10/site-packages/fenbux/__init__.py", line 25, in <module>
    from fenbux.univariate import (
  File "/opt/homebrew/anaconda3/envs/jax/lib/python3.10/site-packages/fenbux/univariate/__init__.py", line 7, in <module>
    from ._censor import (
  File "/opt/homebrew/anaconda3/envs/jax/lib/python3.10/site-packages/fenbux/univariate/_censor.py", line 52, in <module>
    @_censor_impl.dispatch
AttributeError: 'function' object has no attribute 'dispatch'
```

but plum_dispatch=2.2.1 is installed. 

I am already using cola (https://github.com/wilson-labs/cola), which uses cola-plum-dispatch. Could this be an issue?

Edit:- These does seem to be some interaction issue, as uninstall plum_dispatch=2.2.1, reinstalling fenbux with plum_dispatch=2.2.2 breaks cola-ml. Rolling back to plum_dispatch=2.2.1, then break fenbux.

**Comment by JiaYaobo** [comment]
Thanks for reporting it! The issue is because cola contains its version of plum-disptach [cola-plum-dispatch](https://github.com/mfinzi/plum), and it uses the namspace `plum`, so the `plum` namespace will be occupied again and again between installing cola and fenbux. One solution is we can maintain a fenbux version plum-dispatch and use a namespace like `fbx_plum`, does it make sense?

**Comment by JiaYaobo** [comment]
Reclaim in https://github.com/JiaYaobo/fenbux/issues/2, I think it will be solved next version of fenbux

**Comment by JiaYaobo** [comment]
https://github.com/JiaYaobo/fenbux/pull/6 should fix it
